import type { Metadata } from 'next';
import { inter } from '@/ui/fonts';

import './globals.css';
import clsx from 'clsx';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='pt'>
			<body className={clsx(inter.className, 'h-screen antialiased')}>
				{children}
			</body>
		</html>
	);
}
